services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: micro
      POSTGRES_DB: micro
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '19080:8080'